### ISSUE TITLE
Long term Roadmap

### ISSUE THREAD

**Issue by bgailleton** [bgailleton/DAGGER#1]
First stuff to finish on the core:
 
- [x] Finish the porting from old code bases (08991a529e35726f2890d7040f800b55353e0c0b, 33eb5af0cb0ecc83e420de7b3d0f76a41cc507b0, 722493c3ee745548cce383618c5bbdde176c6fb8, 827f176370e04594a94d92964a1c1c60eefb373e, 18230e7985a56b61aa4b67805bf5e032bde88efc)
- [x] Unifying all the graph computation functions into a single function `compute_graph` (a26cda9deb6949efe1b5357864089686d345a5c5)
- [ ] Heavily comment the core (736c7f797b09c633c6af36c4d4342d4ace30a43c, cbd53a33e26bd15fe54052587bd5f900d20f6a6c, ebf29f96e7aa97ad4c85cadd25d6b386442191f2, a24c9329c978fc55054e1adf801f14cde53b8e98, 09571f4443a4ea7c32e1753570cc99eb416d77b0)
- [x] Move all the queries for drainage area or geographical info in the graph to the connector (ca854c36f2a8b473eeea96a5069ccce72a09fddb)
- [x] Clarify naming conventions between `isrec, links, nodes,...` (0930cffda52f3a3824d54d1be04f77329180e985, 6b53d001e1f42484265a01c4415407c072b71317, 2c5fc225b08d59c89985e2faf45c1017385050be, decb2d8d03f14ba61bbcb2e41a0922ab6e088d27, 5cc5d4441a831132865b2ee4acdff1f31b0d295e, a410c63ef86b553aebb5429321a4bdfcca96b966, 532860cac69d5e36b03a155017fd6254bef3969a) [Yo that was tedious!!!]
